name:                six-five-oh-two
version:             0.1.0.0
description:         Dissembler/Emulator for 6502 cpu
author:              Nick Chapman
maintainer:          nic@amadido.co.uk
github:              https://github.com/Nick-Chapman/six-five-oh-two.git

extra-source-files:
- README.md

dependencies:
- array
- base >= 4.7 && < 5
- bytestring
- containers
- extra
- gloss
- mtl
- split
- stt
- time >= 1.9.3
- transformers
- word8

default-extensions:
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiWayIf
- NamedFieldPuns
- NumericUnderscores
- ScopedTypeVariables
- RankNTypes

- NondecreasingIndentation
#- OverloadedStrings
#- RecordWildCards
#- BangPatterns
#- StandaloneDeriving # Is this dangerous in any way?
#- FlexibleInstances

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wno-name-shadowing

executables:
  nes:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -Wall
    - -Wno-name-shadowing
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - six-five-oh-two
