name:                honesty
version:             0.1.0.0
description:         NES Emulator
author:              Nick Chapman
maintainer:          nic@amadido.co.uk
github:              https://github.com/Nick-Chapman/honesty.git

extra-source-files:
- README.md

dependencies:
- array
- base >= 4.7 && < 5
- bytestring
- containers
- extra
- gloss
- mtl
- split
- stt
- time >= 1.9.3
- transformers
- word8

default-extensions:
- DuplicateRecordFields
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiWayIf
- NamedFieldPuns
- NondecreasingIndentation
- NumericUnderscores
- RankNTypes
- ScopedTypeVariables

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -O2
  - -Wno-name-shadowing

executables:
  nes:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -Wall
    - -O2
    - -Wno-name-shadowing
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - honesty
